defaults:
  - model: BERT
  - data: WEBKB

log:
  dir: resource/log/

model_checkpoint:
  dir: resource/model_checkpoint/

prediction:
  dir: resource/prediction/${model.name}_${data.name}/
  fold_id: -1
  write_interval: batch

tsne:
  dir: resource/tsne/${model.name}_${data.name}/
  fold_id: 0

pca:
  dir: resource/pca/${model.name}_${data.name}/
  fold_id: 0

stat:
  dir: resource/stat/

tasks: ["fit","predict", "eval"]

trainer:
  max_epochs: 25
  gpus: 1
  patience: 20
  min_delta: 0.01
  precision: 32
  fast_dev_run: False
  progress_bar_refresh_rate: 1
