name: BERT

encoder:
  _target_: source.encoder.BertEncoder.BertEncoder
  architecture: bert-base-uncased
  output_attentions: False
  pooling:
    _target_: source.pooling.NoPooling.NoPooling

hidden_size: 768

num_classes: ${data.num_classes}

lr: 5e-5
base_lr: 1e-7
max_lr: 1e-3
weight_decay: 1e-2

dropout: 0.1

tokenizer:
  architecture: ${model.encoder.architecture}

loss:
  _target_: source.loss.CrossEntropyLoss.CrossEntropyLoss
  params:
    name: CrossEntropyLoss

stat:
  dir: resource/stat/
  name: ${model.name}_${data.name}.stat