name: BERT

encoder:
  _target_: source.encoder.BertEncoder.BertEncoder
  architecture: bert-base-uncased
  output_attentions: False
  pooling:
    _target_: source.pooling.NoPooling.NoPooling

hidden_size: 768

num_classes: ${data.num_classes}

lr: 5e-5
base_lr: 1e-7
max_lr: 1e-3
weight_decay: 1e-2

dropout: 0.1

tokenizer:
  architecture: ${model.encoder.architecture}


sep_loss: TripletMarginLoss
sep_criterion:
  _target_: source.loss.${model.sep_loss}.${model.sep_loss}
  params:
    name: ${model.sep_loss}
    margin: 1.0
    epsilon: 1e-6
    reduction: mean
    swap: False,
    smooth_loss: False,
    triplets_per_anchor: "all"
    temperature: 0.07

cls_loss: CrossEntropyLoss
cls_criterion:
  _target_: source.loss.${model.cls_loss}.${model.cls_loss}
  params:
    name: ${model.cls_loss}
    margin: 1.0
    epsilon: 1e-6
    reduction: mean
    swap: False,
    smooth_loss: False,
    triplets_per_anchor: "all"
    temperature: 0.07

stat:
  dir: resource/stat/
  name: ${model.name}_${data.name}.stat